### ISSUE TITLE
Filter anomalies

### ISSUE THREAD

**Issue by roata** [roataway/api-documentation#1]
Sometimes the telemetry contains erroneous data. Here we collect the set of known problems, in order to address them later. 

**Note**: when possible, include the tracker ID that produced the problematic payload.

The top post will be updated to include new entries:

- The speed is `255`, which is suspiciously fast for a trolleybus.
- The timestamps may contain redundant 0 characters: `{"latitude":47.027760,"longitude":28.794836,"timestamp":"20190-100-280T90:400:310Z","speed":10,"direction":61.8,"sat":10}`
- Incomplete JSON payloads: `{"latitude":46.995995,"longitude":28.800623,"timesta`

**Comment by default-user-426** [comment]
**broken timestamps**:

- invalid month
`{"latitude":47.027546,"longitude":28.827938,"timestamp":"2019-90-31T12:27:82Z","speed":11,"direction":133.3,"sat":14}`

- invalid day
`{"latitude":46.988281,"longitude":28.885534,"timestamp":"2019-10-00T12:32:41Z","speed":0,"direction":0.0,"sat":14}`

- invalid hour
`{"latitude":46.987492,"longitude":28.885408,"timestamp":"2019-10-31T87:47:17Z","speed":15,"direction":137.9,"sat":14}`

- additional (same) value appended to every ts token
`{"latitude":47.014729,"longitude":28.847136,"timestamp":"201914-1014-3114T714:5314:1014Z","speed":3,"direction":305.4,"sat":14} `

**Comment by default-user-426** [comment]
`2019/11/22 21:59:09 ignoring payload: {"latitude":47.026474,"longitude":28.886356,"timestamp":"2019-11-22T19:59:04Z","speed":0,"direction":214.2,"sat": - reason: unexpected end of JSON input
`

`2019/11/22 19:40:10 ignoring payload: {"latitude":inf,"longitude":28.844278,"timestamp":"2019-11-22T17:40:06Z","speed":0,"direction":0.0,"sat":12} - reason: invalid character 'i' looking for beginning of value
`

`2019/11/22 17:52:25 ignoring payload: {"latitude":47.005592,"longitude":28.867151,"timestamp":"20+19                                   {"latitude":47.005592,"longitude":28.867151,"timestamp":"20+19                                   {"latitude":47.0","speed":0,"direction":0.0,"sat":9} - reason: invalid character 'l' after object key:value pair
`

**Comment by roata** [comment]
- All the data coming from `telemetry/transport/+` is a raw feed from the trackers and is provided "as is".
- All the data coming from `telemetry/route/+` is now post-processed, and the stream will only contain valid messages with correct payloads.


This issue is resolved now. If route-centric telemetry ever comes with bad messages, that's a new issue - please report such payloads, as you did in the past.
